// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────
// Core data structure: one latency measurement
// ─────────────────────────────────────────────
type LatencyMetric struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProbeId        string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	TargetHost     string                 `protobuf:"bytes,2,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	LatencyMs      float64                `protobuf:"fixed64,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TimestampUnix  int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	ProbeType      string                 `protobuf:"bytes,6,opt,name=probe_type,json=probeType,proto3" json:"probe_type,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,7,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LatencyMetric) Reset() {
	*x = LatencyMetric{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyMetric) ProtoMessage() {}

func (x *LatencyMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyMetric.ProtoReflect.Descriptor instead.
func (*LatencyMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LatencyMetric) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *LatencyMetric) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *LatencyMetric) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *LatencyMetric) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *LatencyMetric) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LatencyMetric) GetProbeType() string {
	if x != nil {
		return x.ProbeType
	}
	return ""
}

func (x *LatencyMetric) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// ─────────────────────────────────────────────
// Acknowledgement from collector back to probe
// ─────────────────────────────────────────────
type CollectorAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	MetricsStored int32                  `protobuf:"varint,4,opt,name=metrics_stored,json=metricsStored,proto3" json:"metrics_stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorAck) Reset() {
	*x = CollectorAck{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorAck) ProtoMessage() {}

func (x *CollectorAck) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorAck.ProtoReflect.Descriptor instead.
func (*CollectorAck) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *CollectorAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *CollectorAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CollectorAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *CollectorAck) GetMetricsStored() int32 {
	if x != nil {
		return x.MetricsStored
	}
	return 0
}

// ─────────────────────────────────────────────
// Anomaly alert from ML analytics layer
// ─────────────────────────────────────────────
type AnomalyAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	AnomalyScore  float64                `protobuf:"fixed64,3,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	DetectedAt    int64                  `protobuf:"varint,5,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyAlert) Reset() {
	*x = AnomalyAlert{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyAlert) ProtoMessage() {}

func (x *AnomalyAlert) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyAlert.ProtoReflect.Descriptor instead.
func (*AnomalyAlert) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *AnomalyAlert) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *AnomalyAlert) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AnomalyAlert) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *AnomalyAlert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AnomalyAlert) GetDetectedAt() int64 {
	if x != nil {
		return x.DetectedAt
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"\xf1\x01\n" +
	"\rLatencyMetric\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1f\n" +
	"\vtarget_host\x18\x02 \x01(\tR\n" +
	"targetHost\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x01R\tlatencyMs\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"probe_type\x18\x06 \x01(\tR\tprobeType\x12'\n" +
	"\x0fsequence_number\x18\a \x01(\x05R\x0esequenceNumber\"\x8c\x01\n" +
	"\fCollectorAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12%\n" +
	"\x0emetrics_stored\x18\x04 \x01(\x05R\rmetricsStored\"\xaa\x01\n" +
	"\fAnomalyAlert\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\x12#\n" +
	"\ranomaly_score\x18\x03 \x01(\x01R\fanomalyScore\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1f\n" +
	"\vdetected_at\x18\x05 \x01(\x03R\n" +
	"detectedAt2X\n" +
	"\x10TelemetryService\x12D\n" +
	"\rStreamMetrics\x12\x18.telemetry.LatencyMetric\x1a\x17.telemetry.CollectorAck(\x01BU\n" +
	"\x10com.distro.protoB\x0eTelemetryProtoP\x01Z/github.com/ruruma15/distro-probe/probe-go/protob\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_telemetry_proto_goTypes = []any{
	(*LatencyMetric)(nil), // 0: telemetry.LatencyMetric
	(*CollectorAck)(nil),  // 1: telemetry.CollectorAck
	(*AnomalyAlert)(nil),  // 2: telemetry.AnomalyAlert
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.TelemetryService.StreamMetrics:input_type -> telemetry.LatencyMetric
	1, // 1: telemetry.TelemetryService.StreamMetrics:output_type -> telemetry.CollectorAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
